### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by nayuta723** [nayuta-ai/microservice_go#1]
## Background
We lack knowledge of microservices. So we decided to take Udemy with Working with Microservices in Go (Golang) course.

## Goal
This issue will be closed when I finish taking this course.

### Overview (What, How) 
I plan to take all the classes in this course twice a week.
### Todo
  - [x] Create Environment (Section1)
  - [x] [Build a simple front end and one microservice (Section2)](https://github.com/nayuta-ai/microservice_go/pull/2)
  - [x] [Build an authentication service (Section3)](https://github.com/nayuta-ai/microservice_go/pull/3)
  - [x] [Build a logger service (Section4)](https://github.com/nayuta-ai/microservice_go/pull/3)
  - [x] Build a mail service (Section5)
  - [x] Build a lister service (Section6)
  - [x] Communicate between services using RPC (Section7)
  - [x] Speed things up with gRPC (Section8)
  - [ ] Deploy our distributed apps using Docker Swarm (Section9)
  - [ ] Deploy our distributed apps to Kubernetes (Section10)
  - [ ] Test microservice (Section11)

## Frequency
Twice a week

## Deadline
2022/9

## References
None

## Notes
None

**Comment by nayuta723** [comment]
## Working Time
3h

## Supplement for that task
I watched and implemented section7 and section8. I learned RPC and gRPC.
I will watch and implement a section9 on deploying our distributed apps tomorrow. (estimated time: 4h)
